// Rewrite the instructions in your own words
/* we need to creat a program that given a phrase generates their acronym
//
// Write the objectives and the tests

// Write the pseudocode
we creat 4 var eche var sort the phrase 


// paste your JS generated by blockly below here
