// Rewrite the instructions in your own words
/* we want to creat a computer game to ply rock paper scissors.

// Write the objectives and the tests

// Write the pseudocode
I think we need to set 2 var one for player and one for the computer 
we creat a list with play options.
we need to set as well the rules of the game
we assaign a random play 
we need to set every possible outcome.


// paste your JS generated by blockly below 
