// Rewrite the instructions in your own words

/* we want to creat a computer game to ply rock paper scissors.

// Write the objectives and the tests

// Write the pseudocode

I think we need to set 2 var one for player and one for the computer 
we creat a list with play options.
we need to set rules of the game.
we assaign a random play for the computer.
we need to set every possible outcome.


// paste your JS generated by blockly below 
*/

var player, computer;

function mathRandomInt(a, b) {
  if (a > b) {
    // Swap a and b to ensure a is smaller.
    var c = a;
    a = b;
    b = c;
  }
  return Math.floor(Math.random() * (b - a + 1) + a);
}


player = window.prompt('Please choice btween 1 rock and 2 paper and 3 scissor');
computer = mathRandomInt(1, 3);
if (player == computer) {
  window.alert('tie');
}
if (computer == 1) {
  if (player == 2) {
    window.alert('You Win');
  } else if (player == 3) {
    window.alert('You looooose ');
  }
}
if (computer == 2) {
  if (player == 3) {
    window.alert('You Win');
  } else if (player == 1) {
    window.alert('You looooose ');
  }
}
if (computer == 3) {
  if (player == 1) {
    window.alert('You Win');
  } else if (player == 2) {
    window.alert('You looooose ');
  }
}